/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CpuFeatures {
    #[serde(rename = "amx", skip_serializing_if = "Option::is_none")]
    pub amx: Option<bool>,
}

impl CpuFeatures {
    pub fn new() -> CpuFeatures {
        CpuFeatures { amx: None }
    }
}
