/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceNode {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Vec<serde_json::Value>>,
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<String>>,
    #[serde(rename = "pci_bdf", skip_serializing_if = "Option::is_none")]
    pub pci_bdf: Option<String>,
}

impl DeviceNode {
    pub fn new() -> DeviceNode {
        DeviceNode {
            id: None,
            resources: None,
            children: None,
            pci_bdf: None,
        }
    }
}
