/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DiskImageType : The image type of the disk.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DiskImageType {
    #[serde(rename = "FixedVhd")]
    FixedVhd,
    #[serde(rename = "Qcow2")]
    Qcow2,
    #[serde(rename = "Raw")]
    Raw,
    #[serde(rename = "Vhdx")]
    Vhdx,
}

impl Default for DiskImageType {
    fn default() -> DiskImageType {
        Self::Raw
    }
}
