/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FsConfig {
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "socket")]
    pub socket: String,
    #[serde(rename = "num_queues")]
    pub num_queues: i32,
    #[serde(rename = "queue_size")]
    pub queue_size: i32,
    #[serde(rename = "pci_segment", skip_serializing_if = "Option::is_none")]
    pub pci_segment: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl FsConfig {
    pub fn new(tag: String, socket: String, num_queues: i32, queue_size: i32) -> FsConfig {
        FsConfig {
            tag,
            socket,
            num_queues,
            queue_size,
            pci_segment: None,
            id: None,
        }
    }
}
