/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LandlockConfig {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "access")]
    pub access: String,
}

impl LandlockConfig {
    pub fn new(path: String, access: String) -> LandlockConfig {
        LandlockConfig { path, access }
    }
}
