/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NumaDistance {
    #[serde(rename = "destination")]
    pub destination: i32,
    #[serde(rename = "distance")]
    pub distance: i32,
}

impl NumaDistance {
    pub fn new(destination: i32, distance: i32) -> NumaDistance {
        NumaDistance {
            destination,
            distance,
        }
    }
}
