/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PciDeviceInfo : Information about a PCI device
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PciDeviceInfo {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "bdf")]
    pub bdf: String,
}

impl PciDeviceInfo {
    /// Information about a PCI device
    pub fn new(id: String, bdf: String) -> PciDeviceInfo {
        PciDeviceInfo { id, bdf }
    }
}
