/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitGroupConfig {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "rate_limiter_config")]
    pub rate_limiter_config: Box<models::RateLimiterConfig>,
}

impl RateLimitGroupConfig {
    pub fn new(id: String, rate_limiter_config: models::RateLimiterConfig) -> RateLimitGroupConfig {
        RateLimitGroupConfig {
            id,
            rate_limiter_config: Box::new(rate_limiter_config),
        }
    }
}
