/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiveMigrationData {
    #[serde(rename = "receiver_url")]
    pub receiver_url: String,
}

impl ReceiveMigrationData {
    pub fn new(receiver_url: String) -> ReceiveMigrationData {
        ReceiveMigrationData { receiver_url }
    }
}
