/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendMigrationData {
    #[serde(rename = "destination_url")]
    pub destination_url: String,
    #[serde(rename = "local", skip_serializing_if = "Option::is_none")]
    pub local: Option<bool>,
}

impl SendMigrationData {
    pub fn new(destination_url: String) -> SendMigrationData {
        SendMigrationData {
            destination_url,
            local: None,
        }
    }
}
