/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VdpaConfig {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "num_queues")]
    pub num_queues: i32,
    #[serde(rename = "iommu", skip_serializing_if = "Option::is_none")]
    pub iommu: Option<bool>,
    #[serde(rename = "pci_segment", skip_serializing_if = "Option::is_none")]
    pub pci_segment: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl VdpaConfig {
    pub fn new(path: String, num_queues: i32) -> VdpaConfig {
        VdpaConfig {
            path,
            num_queues,
            iommu: None,
            pci_segment: None,
            id: None,
        }
    }
}
