/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VirtQueueAffinity {
    #[serde(rename = "queue_index")]
    pub queue_index: i32,
    #[serde(rename = "host_cpus")]
    pub host_cpus: Vec<i32>,
}

impl VirtQueueAffinity {
    pub fn new(queue_index: i32, host_cpus: Vec<i32>) -> VirtQueueAffinity {
        VirtQueueAffinity {
            queue_index,
            host_cpus,
        }
    }
}
