/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmResizeDisk {
    /// disk identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// desired disk size in bytes
    #[serde(rename = "desired_size", skip_serializing_if = "Option::is_none")]
    pub desired_size: Option<i64>,
}

impl VmResizeDisk {
    pub fn new() -> VmResizeDisk {
        VmResizeDisk {
            id: None,
            desired_size: None,
        }
    }
}
