/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmResize {
    #[serde(rename = "desired_vcpus", skip_serializing_if = "Option::is_none")]
    pub desired_vcpus: Option<i32>,
    /// desired memory ram in bytes
    #[serde(rename = "desired_ram", skip_serializing_if = "Option::is_none")]
    pub desired_ram: Option<i64>,
    /// desired balloon size in bytes
    #[serde(rename = "desired_balloon", skip_serializing_if = "Option::is_none")]
    pub desired_balloon: Option<i64>,
}

impl VmResize {
    pub fn new() -> VmResize {
        VmResize {
            desired_vcpus: None,
            desired_ram: None,
            desired_balloon: None,
        }
    }
}
