/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmResizeZone {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// desired memory zone size in bytes
    #[serde(rename = "desired_ram", skip_serializing_if = "Option::is_none")]
    pub desired_ram: Option<i64>,
}

impl VmResizeZone {
    pub fn new() -> VmResizeZone {
        VmResizeZone {
            id: None,
            desired_ram: None,
        }
    }
}
