/*
 * Cloud Hypervisor API
 *
 * Local HTTP based API for managing and inspecting a cloud-hypervisor virtual machine.
 *
 * The version of the OpenAPI document: 0.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VmmPingResponse : Virtual Machine Monitor information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmmPingResponse {
    #[serde(rename = "build_version", skip_serializing_if = "Option::is_none")]
    pub build_version: Option<String>,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "pid", skip_serializing_if = "Option::is_none")]
    pub pid: Option<i64>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
}

impl VmmPingResponse {
    /// Virtual Machine Monitor information
    pub fn new(version: String) -> VmmPingResponse {
        VmmPingResponse {
            build_version: None,
            version,
            pid: None,
            features: None,
        }
    }
}
